---
title: "ADF and KPSS tests"
output: html_notebook:
          self_contained: no
---



```{r}
library(portes)
library(parallel)
library(tseries)
library(readr)
library(urca)
```

```{r}
transformed_data <- adf_kpss_transformed
```

```{r}
ha <- transformed_data$X__17
stat.desc(ha, basic=TRUE, desc=TRUE, norm=TRUE, p=0.95)
```



```{r}
plot(transformed_data$X__17, type = 'l', xlab = 'year',  ylab = '')
```




```{r}
ha <- transformed_data$X__6
test <- ur.df(ha, type = "drift", lags = trunc((length(ha)-1)^(1/3)))
summary(test)
#adf.test(transformed_data$X1) #null hypothesis: series contains a unit root
kpss.test(ha, null = "Level") #default null: series is level stationary, put kpss.test(x, null = c("Level", "Trend"), lshort = TRUE) for trend stationary
```


```{r}
test <- ur.df(krippner_ssr_Tr$X1, type = "drift", lags = trunc((length(krippner_ssr_Tr$X1)-1)^(1/3)))
summary(test)
#adf.test(transformed_data$X1) #null hypothesis: series contains a unit root
kpss.test(krippner_ssr_Tr$X1) #default null: series is level stationary, put kpss.test(x, null = c("Level", "Trend"), lshort = TRUE) for trend stationary
```










